const files={ambient:'calm_stream.wav',click:'ui_click.wav',correct:'correct_magic.wav',wrong:'wrong_soft.wav',path:'path_restore.wav',potion:'potion_bubble.wav',speak:'portrait_speaking.wav',reward:'reward.wav',finale:'finale_cue.wav'};

export class Sound{
  constructor(state){this.state=state;this.bank=Object.fromEntries(Object.entries(files).map(([key,file])=>[key,new Audio(`./assets/audio/${file}`)]));this.bank.ambient.loop=true;this.bank.ambient.volume=0;this.started=false;this.voice=null;this.utterance=null;this.fadeFrames={}}
  ambientLevel(){return .055*this.state.volume*this.state.musicVolume}
  fadeTrack(name,target,duration=900){cancelAnimationFrame(this.fadeFrames[name]);const audio=this.bank[name],start=audio.volume,began=performance.now(),step=now=>{const t=Math.min(1,(now-began)/duration);audio.volume=start+(target-start)*(t*t*(3-2*t));if(t<1)this.fadeFrames[name]=requestAnimationFrame(step);else if(target===0)audio.pause()};this.fadeFrames[name]=requestAnimationFrame(step)}
  start(){if(this.started)return;this.started=true;if(this.state.soundEnabled&&this.state.musicEnabled)this.bank.ambient.play().then(()=>this.fadeTrack('ambient',this.ambientLevel(),2200)).catch(()=>{})}
  play(name){if(!this.state.soundEnabled||!this.state.sfxEnabled)return;const audio=this.bank[name];if(!audio)return;audio.currentTime=0;audio.volume=(name==='wrong'?.45:1)*this.state.volume*this.state.sfxVolume;audio.play().catch(()=>{})}
  speak(text,index){this.stopVoice();if(!this.state.soundEnabled)return;const synth=window.speechSynthesis;if(synth&&window.SpeechSynthesisUtterance){const utterance=new SpeechSynthesisUtterance(text),voices=synth.getVoices().filter(v=>/^en[-_]/i.test(v.lang));const preferred=['Samantha','Ava','Serena','Sonia','Karen','Moira','Google UK English Female'];utterance.voice=preferred.map(name=>voices.find(v=>v.name.includes(name))).find(Boolean)||voices.find(v=>v.localService)||voices[0]||null;utterance.lang=utterance.voice?.lang||'en-GB';utterance.rate=.86;utterance.pitch=1.02;utterance.volume=this.state.volume*this.state.voiceVolume;utterance.onend=()=>{if(this.utterance===utterance)this.utterance=null};utterance.onerror=e=>{if(this.utterance===utterance&&!['interrupted','canceled'].includes(e.error))this.playRecordedVoice(index)};this.utterance=utterance;synth.speak(utterance);return}this.playRecordedVoice(index)}
  playRecordedVoice(index){this.voice=new Audio(`./assets/audio/voices/line_${String(index+1).padStart(2,'0')}.m4a`);this.voice.volume=this.state.volume*this.state.voiceVolume;this.voice.play().catch(()=>{})}
  sync(){if(this.state.soundEnabled&&this.state.musicEnabled&&this.started)this.bank.ambient.play().then(()=>this.fadeTrack('ambient',this.ambientLevel())).catch(()=>{});else this.fadeTrack('ambient',0,450);if(!this.state.soundEnabled)this.stopVoice()}
  stopVoice(){if(window.speechSynthesis)window.speechSynthesis.cancel();this.utterance=null;if(this.voice){this.voice.pause();this.voice.currentTime=0;this.voice=null}}
}
