const files={ambient:'forest_ambient_loop.wav',click:'ui_click.wav',correct:'correct_magic.wav',wrong:'wrong_soft.wav',path:'path_restore.wav',potion:'potion_bubble.wav',speak:'portrait_speaking.wav',reward:'reward.wav',finale:'finale_cue.wav'};

class FairyScore{
  constructor(){this.ctx=null;this.bus=null;this.master=null;this.timer=0;this.nextBar=0;this.bar=0}
  ensure(){if(this.ctx)return;const AudioContext=window.AudioContext||window.webkitAudioContext;if(!AudioContext)return;this.ctx=new AudioContext();this.bus=this.ctx.createGain();this.master=this.ctx.createGain();this.master.gain.value=0;const delay=this.ctx.createDelay(2),feedback=this.ctx.createGain(),wet=this.ctx.createGain();delay.delayTime.value=.42;feedback.gain.value=.18;wet.gain.value=.22;this.bus.connect(this.master);this.bus.connect(delay);delay.connect(wet).connect(this.master);delay.connect(feedback).connect(delay);this.master.connect(this.ctx.destination)}
  note(freq,start,duration=.8,volume=.028,type='triangle'){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();o.type=type;o.frequency.setValueAtTime(freq,start);filter.type='lowpass';filter.frequency.value=1800;g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(volume,start+.035);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(filter).connect(g).connect(this.bus);o.start(start);o.stop(start+duration+.05)}
  pad(freq,start,duration=8){const o=this.ctx.createOscillator(),g=this.ctx.createGain(),filter=this.ctx.createBiquadFilter();o.type='sine';o.frequency.value=freq;filter.type='lowpass';filter.frequency.value=720;g.gain.setValueAtTime(.0001,start);g.gain.exponentialRampToValueAtTime(.018,start+1.4);g.gain.setValueAtTime(.018,start+duration-1.8);g.gain.exponentialRampToValueAtTime(.0001,start+duration);o.connect(filter).connect(g).connect(this.bus);o.start(start);o.stop(start+duration+.1)}
  schedule(){if(!this.ctx||!this.timer)return;const chords=[[146.83,185,220],[123.47,146.83,185],[98,123.47,146.83],[110,138.59,164.81]],melodies=[[587.33,739.99,880,739.99,659.25,587.33],[493.88,587.33,739.99,659.25,587.33,493.88],[440,587.33,739.99,587.33,493.88,440],[554.37,659.25,880,739.99,659.25,554.37]];while(this.nextBar<this.ctx.currentTime+10){const chord=chords[this.bar%chords.length],melody=melodies[this.bar%melodies.length],start=this.nextBar;chord.forEach((f,i)=>this.pad(f,start+i*.08,8.6));[.7,2.05,3.35,4.9,6.25,7.45].forEach((offset,i)=>this.note(melody[i],start+offset,i===5?1.5:.9,i%3===0?.032:.024,i%2?'sine':'triangle'));this.note(chord[0]*2,start+4.15,1.8,.018,'sine');this.nextBar+=8.5;this.bar++}}
  start(volume){this.ensure();if(!this.ctx)return;if(this.ctx.state==='suspended')this.ctx.resume();this.master.gain.cancelScheduledValues(this.ctx.currentTime);this.master.gain.setTargetAtTime(volume,this.ctx.currentTime,.8);if(this.timer)return;this.nextBar=this.ctx.currentTime+.12;this.timer=setInterval(()=>this.schedule(),2500);this.schedule()}
  setVolume(volume){if(this.master)this.master.gain.setTargetAtTime(volume,this.ctx.currentTime,.5)}
  stop(){if(!this.ctx)return;this.master.gain.setTargetAtTime(0,this.ctx.currentTime,.35);clearInterval(this.timer);this.timer=0}
}

export class Sound{
  constructor(state){this.state=state;this.bank=Object.fromEntries(Object.entries(files).map(([key,file])=>[key,new Audio(`./assets/audio/${file}`)]));this.bank.ambient.loop=true;this.bank.ambient.playbackRate=.92;if('preservesPitch'in this.bank.ambient)this.bank.ambient.preservesPitch=false;this.bank.ambient.volume=0;this.score=new FairyScore();this.started=false;this.voice=null;this.utterance=null;this.fadeFrame=0}
  ambientLevel(){return .028*this.state.volume*this.state.musicVolume}
  scoreLevel(){return .7*this.state.volume*this.state.musicVolume}
  fadeAmbient(target,duration=900){cancelAnimationFrame(this.fadeFrame);const audio=this.bank.ambient,start=audio.volume,began=performance.now(),step=now=>{const t=Math.min(1,(now-began)/duration);audio.volume=start+(target-start)*(t*t*(3-2*t));if(t<1)this.fadeFrame=requestAnimationFrame(step);else if(target===0)audio.pause()};this.fadeFrame=requestAnimationFrame(step)}
  start(){if(this.started)return;this.started=true;if(this.state.soundEnabled&&this.state.musicEnabled){this.bank.ambient.play().then(()=>this.fadeAmbient(this.ambientLevel(),1800)).catch(()=>{});this.score.start(this.scoreLevel())}}
  play(name){if(!this.state.soundEnabled||!this.state.sfxEnabled)return;const audio=this.bank[name];if(!audio)return;audio.currentTime=0;audio.volume=(name==='wrong'?.45:1)*this.state.volume*this.state.sfxVolume;audio.play().catch(()=>{})}
  speak(text,index){this.stopVoice();if(!this.state.soundEnabled)return;const synth=window.speechSynthesis;if(synth&&window.SpeechSynthesisUtterance){const utterance=new SpeechSynthesisUtterance(text),voices=synth.getVoices().filter(v=>/^en[-_]/i.test(v.lang));const preferred=['Samantha','Ava','Serena','Sonia','Karen','Moira','Google UK English Female'];utterance.voice=preferred.map(name=>voices.find(v=>v.name.includes(name))).find(Boolean)||voices.find(v=>v.localService)||voices[0]||null;utterance.lang=utterance.voice?.lang||'en-GB';utterance.rate=.86;utterance.pitch=1.02;utterance.volume=this.state.volume*this.state.voiceVolume;utterance.onend=()=>{if(this.utterance===utterance)this.utterance=null};utterance.onerror=e=>{if(this.utterance===utterance&&!['interrupted','canceled'].includes(e.error))this.playRecordedVoice(index)};this.utterance=utterance;synth.speak(utterance);return}this.playRecordedVoice(index)}
  playRecordedVoice(index){this.voice=new Audio(`./assets/audio/voices/line_${String(index+1).padStart(2,'0')}.m4a`);this.voice.volume=this.state.volume*this.state.voiceVolume;this.voice.play().catch(()=>{})}
  sync(){if(this.state.soundEnabled&&this.state.musicEnabled&&this.started){this.bank.ambient.play().then(()=>this.fadeAmbient(this.ambientLevel())).catch(()=>{});this.score.start(this.scoreLevel());this.score.setVolume(this.scoreLevel())}else{this.fadeAmbient(0,450);this.score.stop()}if(!this.state.soundEnabled)this.stopVoice()}
  stopVoice(){if(window.speechSynthesis)window.speechSynthesis.cancel();this.utterance=null;if(this.voice){this.voice.pause();this.voice.currentTime=0;this.voice=null}}
}
